### ISSUE TITLE
Is there a way to pass arguments to a grunt task?

### ISSUE THREAD

**Issue by sivakuna-aap** [noseglid/atom-build-grunt#3]
How to pass arguments for a grunt task? At the moment, the task starts running the moment the task is selected.

**Comment by noseglid** [comment]
There's no option to do this. If you need to customize the build further than just calling `grunt <task>`, you should add [a custom build command](https://github.com/noseglid/atom-build#specifying-a-custom-build-command).

**Comment by sivakuna-aap** [comment]
OK, thanks for the help.
